swagger: "2.0"
info:
  version: 1.0.0
  title: Swagger Petstore
  license:
    name: MIT
host: localhost:8888
basePath: /stamp
schemes:
  - http
consumes:
  - application/json
  - multipart/form-data
produces:
  - application/json
  - multipart/form-data
paths:
  /verify:
    post:
      summary: List all pets
      operationId: listPets
      tags:
        - 认证
      parameters:
        - name: file
          in: formData
          description: How many items to return at one time (max 100)
          required: true
          type: file
#          format: int32
      responses:
        "200":
          description: An paged array of pets
          headers:
            x-next:
              type: string
              description: A link to the next page of responses
          schema:
            $ref: '#/definitions/judgeResult'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/Error'
definitions:
  judgeResult:
    required:
      - result
    properties:
      result:
        type: boolean
        format: boolean
  Error:
    required:
      - code
      - message
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string